package com.example.guitarchordassistant.data

import android.os.Parcel
import android.os.Parcelable
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import java.io.Serializable

/**
 * data class entity which models the SQLite database
 */
@Entity
data class Chord(
    // declare id as autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    val chordId: Int,
    val name: String,
    val sound: String,
    val type: String
)
/*
@Entity(
    foreignKeys = [ForeignKey(
        entity = Chord::class,
        parentColumns = arrayOf("chordId"),
        childColumns = arrayOf("chordId"),
        onDelete = ForeignKey.NO_ACTION
    )]
)
*/
