package com.example.guitarchordassistant.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

@Entity
data class Image(
    // declare id as autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    val imageId: Int,
    val imageName: String,
    val chordId: Int
): Serializable
